# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    env:
      buildConfiguration: 'Release'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    # Run the Cake build script
    - name: Run Cake build script
      run: .\build.ps1 --target=Default --verbosity=minimal
      shell: powershell

    #- uses: cake-build/cake-action@v2.0.0
    #- name: Build Cakke      
    #  with:
    #    script-path: 'build.cake'
    #    target: 'Default'
    #    verbosity: 'Minimal'

    # Publish artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: ${{ github.workspace }}/publish
